---
- name: Allow ssh traffic to ipv4
  ansible.builtin.iptables:
    action: append
    chain: INPUT
    jump: ACCEPT
    protocol: tcp
    destination_port: "{{ ansible_port }}"
    comment: An exception to accept ssh traffic
    ip_version: "ipv4"

- name: Allow ssh traffic to ipv6
  ansible.builtin.iptables:
    action: append
    chain: INPUT
    jump: ACCEPT
    protocol: tcp
    destination_port: "{{ ansible_port }}"
    comment: An exception to accept ssh traffic
    ip_version: "ipv6"

- name: Allow established traffic for ipv4
  ansible.builtin.iptables:
    action: append
    chain: INPUT
    jump: ACCEPT
    ctstate: ESTABLISHED,RELATED
    comment: An exception to accept all traffic that is part of an established connection or is related to an established connection
    ip_version: "ipv4"

- name: Allow established traffic for ipv6
  ansible.builtin.iptables:
    action: append
    chain: INPUT
    jump: ACCEPT
    ctstate: ESTABLISHED,RELATED
    comment: An exception to accept all traffic that is part of an established connection or is related to an established connection
    ip_version: "ipv6"

- name: Allow traffic to lo for ipv4
  ansible.builtin.iptables:
    action: append
    chain: INPUT
    jump: ACCEPT
    in_interface: lo
    comment: Allow all traffic originating on the local loopback interface
    ip_version: "ipv4"

- name: Allow traffic to lo for ipv4
  ansible.builtin.iptables:
    action: append
    chain: INPUT
    jump: ACCEPT
    in_interface: lo
    comment: Allow all traffic originating on the local loopback interface
    ip_version: "ipv6"

- name: Allow traffic to Apache
  ansible.builtin.iptables:
    chain: INPUT
    jump: ACCEPT
    in_interface: wg1
    protocol: tcp
    destination_port: 8080
    state: present

- name: Drop all ipv4 inbound traffic
  ansible.builtin.iptables:
    action: append
    chain: INPUT
    policy: DROP
    ip_version: "ipv4"

- name: Drop all ipv6 inbound traffic
  ansible.builtin.iptables:
    action: append
    chain: INPUT
    policy: DROP
    ip_version: "ipv6"

- name: Save current state of the firewall in system file v4
  community.general.iptables_state:
    state: saved
    path: /etc/iptables/rules.v4

- name: Save current state of the firewall in system file v6
  community.general.iptables_state:
    ip_version: ipv6
    state: saved
    path: /etc/iptables/rules.v6
