---
- name: Upgrade Ubuntu
  ansible.builtin.apt:
    update_cache: true
    upgrade: dist
    autoclean: true
    autoremove: true
    clean: true

- name: Purge snapd, ufw
  ansible.builtin.apt:
    name:
      - snapd
    state: absent
    purge: true

- name: Delete snapd dir
  ansible.builtin.file:
    state: absent
    path: /snap

- name: Install common tools
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: present
    update_cache: true

# Configure SSHD
- name: Include sshd.yaml
  ansible.builtin.include_tasks: sshd.yaml

# Configure Fail2ban
- name: Include fail2ban.yaml
  ansible.builtin.include_tasks: fail2ban.yaml

# Configure ufw
- name: Include ufw.yaml
  ansible.builtin.include_tasks: ufw.yaml
