---
- name: Create directory for keyrings
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Delete old gpg
  ansible.builtin.file:
    path: /etc/apt/keyrings/docker.gpg
    state: absent

- name: Download Docker GPG key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /tmp/docker.gpg
    mode: '0644'

- name: Armor Docker GPG key
  ansible.builtin.command: gpg --dearmor -o /etc/apt/keyrings/docker.gpg /tmp/docker.gpg
  register: command_output
  changed_when: command_output.rc != 0

- name: Add Docker repository to apt sources
  ansible.builtin.lineinfile:
    path: /etc/apt/sources.list.d/docker.list
    line: "deb [arch=arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ['ansible_lsb']['codename'] }} stable"
    create: true
    state: present
    mode: '0644'

- name: Upgrade Ubuntu
  ansible.builtin.apt:
    update_cache: true
    upgrade: dist
    autoclean: true
    autoremove: true
    clean: true

- name: Purge snapd
  ansible.builtin.apt:
    name:
      - snapd
    state: absent
    purge: true

- name: Delete snapd dir
  ansible.builtin.file:
    state: absent
    path: /snap

- name: Install common tools
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: present
    update_cache: true

- name: Configure sysctl parameters
  ansible.posix.sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
  with_items:
    - { key: 'net.ipv4.ip_forward', value: 1 }
    - { key: 'net.ipv6.conf.all.forwarding', value: 1 }

# Configure SSHD
- name: Include sshd.yaml
  ansible.builtin.include_tasks: sshd.yaml

# Configure Fail2ban
- name: Include fail2ban.yaml
  ansible.builtin.include_tasks: fail2ban.yaml

# Configure UFW
- name: Include ufw.yaml
  ansible.builtin.include_tasks: ufw.yaml
