---
- name: Start wg0 after iptables setup
  ansible.builtin.systemd:
    name: wg-quick@wg0.service
    state: started
  when: vpn_wg0 == "true"
  ignore_errors: true
  register: ignore_errors_register

- name: Start wg1 after iptables setup
  ansible.builtin.systemd:
    name: wg-quick@wg1.service
    state: started
  ignore_errors: true
  register: ignore_errors_register

- name: Start Docker after iptables setup
  ansible.builtin.systemd:
    name: docker.service
    state: started
  when: vpn_role == "main"
  ignore_errors: true
  register: ignore_errors_register

- name: Start Prometheus after iptables setup
  ansible.builtin.systemd:
    name: prometheus.service
    state: started
  when: vpn_role == "main"
  ignore_errors: true
  register: ignore_errors_register

- name: Start Grafana after iptables setup
  ansible.builtin.systemd:
    name: grafana.service
    state: started
  when: vpn_role == "main"
  ignore_errors: true
  register: ignore_errors_register

- name: Start fail2ban before iptables setup
  ansible.builtin.systemd:
    name: fail2ban.service
    state: started
  ignore_errors: true
  register: ignore_errors_register
