---
- name: Open SSH port
  community.general.ufw:
    port: "{{ ansible_port }}"
    rule: allow
    proto: tcp
    comment: SSH

- name: Enable UFW
  community.general.ufw:
    state: enabled
    policy: reject

- name: Allow everything and enable UFW
  community.general.ufw:
    state: enabled
    direction: routed
    policy: allow

- name: Open wg0 port
  community.general.ufw:
    port: "{{ vpn_wg0_port }}"
    rule: allow
    proto: udp
    comment: WG0 iface port
  when: vpn_wg0 == "true"

- name: Open wg1 port
  community.general.ufw:
    port: "{{ vpn_wg1_port }}"
    rule: allow
    proto: udp
    comment: WG1 iface port
  when: vpn_role == "main"

- name: Allow traffic to wg1 iface
  community.general.ufw:
    interface: wg1
    direction: in
    rule: allow

- name: Allow traffic to wg0 iface
  community.general.ufw:
    interface: wg0
    direction: in
    rule: allow
  when: vpn_wg0 == "true"

- name: Allow traffic to docker0 iface
  community.general.ufw:
    interface: docker0
    direction: in
    rule: allow

- name: Allow routing between wg0 and wg1
  community.general.ufw:
    rule: allow
    route: true
    interface_in: wg0
    interface_out: wg1
  when: vpn_wg0 == "true"

- name: Enable UFW service
  ansible.builtin.systemd:
    name: ufw.service
    state: started
    enabled: true
